config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :filesystems do
  	resources :comments do
  		get :delete
  	end
  end
  resources :notifications
  get 'filesystems/my_file'
  root 'filesystems#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user, dependent: :destroy
	belongs_to :filesystem, dependent: :destroy
	validates :content, presence: true
end

app/models/filesystem.rb
class Filesystem < ApplicationRecord
	after_create :create_notification
	after_update :update_notification
	before_destroy :destroy_notification
	belongs_to :user
	has_many :comments
	has_many :notifications
	validates :file_name, presence: true
	has_one_attached :image
	validates :image, presence: true
	enum status: { public_status:0, private_status: 1 } 

	def create_notification
		notifications.create(title: "You uploaded #{file_name} ", user_id: self.user.id)
	end

	def update_notification
		notifications.create(title: "You updated #{file_name}", user_id: self.user.id)
	end

	def destroy_notification
		notifications.create(title: "You deleted #{file_name}", user_id: self.user.id)
	end

	def increase_visit(user)
		unless user == self.user
    	self.visit_counter += 1
    	save!
    	notifications.create(title: "viewed #{file_name}", user_id: self.user.id)
    end
    end
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :filesystem, dependent: :destroy
	belongs_to :user
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :filesystems
         has_many :comments
         has_many :notifications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_file, only: [:create, :destroy]
	def create
		@comment = @file.comments.new(comment_params)
		if @comment.save
			flash[:notice] = 'comment uploaded!'
			redirect_to @file
		else
			flash[:notice] = 'comment faild to load!'
			redirect_to @file
		end
	end

	def destroy
		@comment = @filesystem.comments.find(params[:id])
		if @comment.destroy
			flash[:notice] = 'file deleted!'
		redirect_to @file
	else
		flash[:notice] = 'file not deleted!'
	end
	end

	private
	def comment_params
		params.require(:comment).permit(:filesystem_id, :content, :user_id)
	end

	def find_file
		@file = Filesystem.find_by_id(params[:filesystem_id])
	end
end

app/controllers/filesystems_controller.rb
class FilesystemsController < ApplicationController
	before_action :find_filesystem, only: [:show, :update, :edit, :destroy]
	def index
		@files = Filesystem.order(created_at: :desc)
	end

	def new
		@file = Filesystem.new
	end

	def create
		@file = Filesystem.new(file_params)
		if @file.save
			flash[:notice] = "File created!"
			redirect_to filesystems_path
		else
			flash[:alert] = "File not created!"
			redirect_to new_filesystem_path
		end
	end

	def show
		@comment = Comment.new
		if @file.blank?
			redirect_to filesystems_path
			flash[:alert] = 'file not found!'		
		else
		@file.increase_visit(current_user)
	end
	end

	def edit
	end

	def update
		if @file.update(file_params)
			flash[:notice] = 'file updated!'
		else
			flash[:alert] = 'file not updated!'
		end
		redirect_to filesystem_path
	end


	def destroy
		if @file.destroy
			flash[:notice] = 'file deleted!'
		else
			flash[:alert] = 'file not deleted'
		end
		redirect_to filesystems_path
	end

	private
	def file_params
		params.require(:filesystem).permit(:file_name, :status, :image, :user_id)
	end

	def find_filesystem
		@file = Filesystem.find_by_id(params[:id])
	end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	def index
		@notification = Notification.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/filesystems_helper.rb
module FilesystemsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/comments/_comment.html.erb
<style>
	.comment{
		background-color: #f1f3f8;
	}
</style>
<% @file.comments.each do |f| %>
<% if @file.user == current_user %>
<div class="container comment">
	<h4><b><%= f.filesystem.user.email %></b></h4>
	<h3>
		<%= f.content %>
	</h3>	
</div>
<br>
<% end %>
<% end %>	

app/views/comments/_form.html.erb
<div class="container">	
  	<div class="form-group">
  		<h3>Comment</h3>
 		<%= form_for [@file, @comment ] do |f| %>
		<%= f.text_area :content, :class => "form-control" %>
		<%= f.hidden_field :user_id, value: current_user.id %>
		<br>
		<%= f.submit "comment", :class => "bnt btn-primary" %>
		<% end %>
	</div>

app/views/filesystems/edit.html.erb
<%= form_for @file do |f| %>
	<%= f.label :File_Name %>
	<%= f.text_field :file_name %><br><br>
	<%= f.select :status, ["public_status","private_status"]%><br><br>
	<%= f.file_field :image %><br>
	<%= f.submit 'update file' %>
<% end %>

app/views/filesystems/index.html.erb
<%= link_to "Add file", new_filesystem_path, class: "btn btn-primary" %>
<h1>All files</h1>
<br>
<br>
<div class="container">
	<h3><span class="badge badge-secondary" style="font-size:20px;"><%= @files.count %></span>Files</h3><br>
	<% @files.each do |f| %>
	<% unless f.status == "private_status" && f.user.id != current_user.id %>
	<%= link_to :controller => "filesystems", :action => "show", :id => f.id do%>
	<div class="jumbotron jumbotron-fluid" style="height: 200px">

		<h1><%= f.file_name.titleize %></h1>
		<h4><%= f.status %></h4>
		<h4>Owner Email:<b><%= f.user.email %></b></h4>
	</div>
	<% end %>
	<% end %>
	<br>
	<br>
	<% end %>
</div>

app/views/filesystems/new.html.erb
<div class="container">
	<%= form_for @file do |f| %>
	<div class="form-group">
		<%= f.label :File_Name, :class => "sr-only" %>
		<%= f.text_field :file_name, :class => "form-control" %><br><br>
		<%= f.hidden_field :user_id, value: current_user.id %>
		<%= f.select :status, ["public_status","private_status"],{:class => "costom-select"}%><br><br>
		<%= f.file_field :image %><br><br>
		<%= f.submit 'Create file', :class => "btn btn-primary" %>
	</div>
	<% end %>
</div>

app/views/filesystems/show.html.erb
<style>
	.img{
		height: 200px;
		width: 200px;
	}
</style>
<% if @file.present? %>
<%= filesystem_url %>
<div class="container">
	<% if @file.user == current_user %>
	<%= button_to "Delete", filesystem_path , :method => :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-danger"%>
	<br>
	<%= link_to "edit", edit_filesystem_path, :class => "btn btn-warning" %>
	<br>
	<% end %>
	<div class="row">
		<div class="col-sm-6">
			<h3><span class="badge badge-secondary" style="font-size:20px;"><%= @file.visit_counter %></span>Views</h3>
			<h3></h3>
			<h3><b>File Name:</b><%= @file.file_name %></h3>
			<br>
			<h3><b>File status:</b><%= @file.status %></h3>
			<br>
			<h3><b>File Owner:</b><%= @file.user.email %></h3>
		</div>
		<div class="col-sm-6">
			<%= image_tag(@file.image, :class => "img") if @file.image.attached? %>
		</div>
	</div>	
</div>
<% end %>
<br>
<br>

<br>
<br>
<div class="container">
	<h3><%= @file.comments.count %>Comments</h3>
	<%= render 'comments/comment', :locals => {:comments => Comment.all} %>
</div>
<%= render 'comments/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileSharing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'FileSharingSystem', root_path, class: 'navbar-link' %>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to 'Home', filesystems_path %></li>
      <li><%= link_to 'Add Files', new_filesystem_path %></li>
      <li><%= link_to 'Notifications', notifications_path %></li>
    </ul>
     <ul class="nav navbar-nav pull-right">
      <p class="navbar-text float-right">
    <% if user_signed_in? %>
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
    </ul>
  </div>
  </nav>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/notifications/index.html.erb
<h2>All notifications</h2>
<% current_user.notifications.reverse_each do |f| %>
<div class="alert alert-info container">
	<strong>
		<%= f.title %>
	</strong>
</div>
<% end %>